server:
  port: 8080
spring:
  application:
    # 配置访问名称，默认为工程名
    name: reggie
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://43.143.246.214:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: xuanyunyi645134
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\1临时文件\Riggie\img\
aliyun:
  accessKeyId: LTAI5tHaxArL7CaY5Q7QxH3v
  secret: B8wlAPPCTfJijXLECDaSR07kkvXvAA